version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5001"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/sistema-cuentas
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
